### PR TITLE
Fixed unintuitive fineness behaviour

### PR DESCRIPTION
**Pull request by Stefan-Heimersheim**
# Description

Fixes issue #13 by making fineness behaviour more intuitive, i.e. the default filled color contour levels for e.g. fineness=0.5 and contours [1,2] are now `[0.5,1,1.5,2,2]` instead of `[0.5,1,1.5,2,2,2.5]`.

Edit: Also quite visible in the colorbar, e.g. for [1,2] sigma contours. It now stretches from 0 to 2 sigma, instead of from 0 to 2.75 sigma (fineness=0.25):
Figure_1

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

I guess it is technically breaking as the `default_color_levels` arguments will work slightly different.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] `test_plot_fineness()` in `test_plot.py`
- [x]  Tested it in my own codes
- [x] `cbar = plot(x, y, z, ax, fineness=0.5, contour_line_levels=[1,2])` looks as expected
Figure_1
- [x] `cbar = plot(x, y, z, ax, fineness=0.3, contour_line_levels=[1,2])` (no one would use non-integer levels/fineness but just to check) looks as expected:
Figure_1

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Stefan-Heimersheim** [comment]
I think I'm happy with this now, only not completely sure about the formatting of the docstring (added line break due to width limit).

**Review by williamjameshandley — CHANGES_REQUESTED** [review]
I think that this is a much more sensible behaviour

As this is a defaults change could you bump the [version number](https://semver.org/) in the README to 2.4.0, and I'll then update the pip from that once it's merged. Could you also re-run the examples in the readme so that the figures are updated?

**Comment by Stefan-Heimersheim** [comment]
Sorry for the delay here as well, I bumped the version and reran the plots.

Note that my plot boundaries were different (x axis went to [-20,20] in all plots) so I added

```python
ax_samples.set_xlim(-20,20)
ax_samples.set_ylim(-20,20)
ax_lines.set_xlim(-2,2)
ax_fgivenx.set_xlim(-2,2)
ax_dkl.set_xlim(-2,2)
```

to the first plot, it still changes the limits of the plots but just slightly.

**Review by williamjameshandley — APPROVED** [review]
Many thanks @Stefan-Heimersheim. Please squash and merge.

**Pull request merged**
